const BUILTIN_SKILLS = [
  {
    name: "review",
    description: "生成结构化代码评审提示词与检查清单",
    targetTools: ["claude", "codex"],
    requiredFields: ["goal"],
    template: [
      "你是资深代码评审工程师。",
      "目标：{{goal}}",
      "范围：{{scope}}",
      "仓库上下文：{{context}}",
      "",
      "请按以下结构输出：",
      "1) 关键风险（按优先级）",
      "2) 需求覆盖与边界遗漏",
      "3) 测试缺口与回归风险",
      "4) 可执行修复建议（最小改动优先）",
    ].join("\n"),
    defaults: {
      scope: "未指定",
      context: "无额外上下文",
    },
  },
  {
    name: "spec",
    description: "生成功能方案文档（目标/范围/里程碑/风险）",
    targetTools: ["claude", "codex"],
    requiredFields: ["feature"],
    template: [
      "请为以下需求编写实施方案（Spec）：",
      "功能：{{feature}}",
      "业务目标：{{goal}}",
      "约束：{{constraints}}",
      "",
      "输出要求：",
      "- 背景与目标",
      "- 范围（做什么/不做什么）",
      "- 技术方案（最小可行）",
      "- 任务拆分（可执行）",
      "- 风险与回滚",
    ].join("\n"),
    defaults: {
      goal: "提升交付效率并保证质量",
      constraints: "无",
    },
  },
  {
    name: "release-check",
    description: "生成发布前检查清单",
    targetTools: ["claude", "codex"],
    requiredFields: ["version"],
    template: [
      "请生成版本发布前检查清单。",
      "目标版本：{{version}}",
      "发布范围：{{scope}}",
      "",
      "检查项至少包含：",
      "- 变更日志完整性",
      "- 测试覆盖与回归",
      "- 安装/升级路径验证",
      "- 回滚方案",
      "- 发布后观测指标",
    ].join("\n"),
    defaults: {
      scope: "best-practice-skill",
    },
  },
  {
    name: "best-practice",
    description: "检索并汇总指定功能的代码最佳实践",
    targetTools: ["claude", "codex"],
    requiredFields: ["topic"],
    template: [
      "你是最佳实践研究助手。",
      "主题：{{topic}}",
      "技术栈：{{stack}}",
      "目标：{{objective}}",
      "",
      "请先执行以下命令获取研究报告：",
      "npx best-practice-skill practice search --input '{\"topic\":\"{{topic}}\",\"stack\":\"{{stack}}\",\"objective\":\"{{objective}}\"}'",
      "",
      "然后按以下结构输出：",
      "1) Top 实践清单（附来源）",
      "2) Do / Don't",
      "3) 最小可行实现步骤",
      "4) 测试与回归清单",
      "5) 风险与版本兼容提示",
    ].join("\n"),
    defaults: {
      stack: "通用",
      objective: "实现高质量、可维护、可测试的代码方案",
    },
  },
];

module.exports = {
  BUILTIN_SKILLS,
};
